[database]
    ip = "39.99.140.114"
    port = "3306"
    username = "root"
    password = "whibin"
    database = "dream"
    conf = "charset=utf8&parseTime=True&loc=Local"

[http]
    port = "8080"
    prefix-url = "http://39.99.140.114"

[other]
    local-path-prefix = "/usr/local/dream"
