[mysql]
    ip = "39.99.140.114"
    port = "3306"
    username = "root"
    password = "whibin"
    database = "dream"
    variables = "charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=True&loc=Local"

[redis]
    ip = "39.99.140.114"
    port = "6379"
    password = "whibin"

[http]
    web-port = "8080"

[other]
    prefix-url = "https://common.qgailab.com"
    local-path-prefix = "/usr/local/dream"