[mysql]
    ip = "39.99.140.114"
    port = "3306"
    username = "root"
    password = "whibin"
    database = "dream"
    variables = "charset=utf8&parseTime=True&loc=Local"

[redis]
    ip = "39.99.140.114"
    port = "6379"
    password = "whibin"

[http]
    web-port = "8081"

[other]
    prefix-url = "http://39.99.140.114"
    local-path-prefix = "/usr/local/dream"